### ISSUE TITLE
no support for RepeatingGroup tags?

### ISSUE THREAD

**Issue by ghost** [atdl4net/atdl4net#4]
Hello,

   If I have any parameters nested in a RepeatingGroup tag, the application does not seem to be able to "see" these parameters.

Example: 

`
 <RepeatingGroup name="NoLegs" minSize="1" fixTag="555">
<Parameter name="LegSymbol1" xsi:type="String_t" fixTag="600" use="required" mutableOnCxlRpl="false" />
</RepeatingGroup>
`

If I remove the `<RepeatingGroup>` tags, the issue goes away, but then I'm not sure the outbound FIX message will be correctly constructed.  Am I doing this incorrectly, or is this functionality not supported?

![image](https://user-images.githubusercontent.com/68879812/88603711-4eaf9880-d03b-11ea-95c1-c13f90970f3e.png)

**Comment by atdl4net** [comment]
Could you please post a code sample (ideally something I can just load into VS and run)?

**Comment by ghost** [comment]
github won't let me upload the file as XML, but I just changed it to a TXT


If you remove the RepeatingGroup tags around those parameters, then the app is able to render.  However, it has the above issue if they are not removed.

[github test.txt](https://github.com/atdl4net/atdl4net/files/4996006/github.test.txt)

**Comment by atdl4net** [comment]
Hi.  Looking at the code (which I wrote nearly 10 years ago), it doesn't looking the RepeatingGroups tag is properly supported.  I can't imagine it's too scary to implement, but I probably won't get to it for a little while.  I checked all the forks out there and no one seems to have tackled this, so you'll either have to tackle yourself (feel free to send a pull request if you do) or wait for me to implement.

Sorry for the oversight.

**Comment by ghost** [comment]
No worries, based on a thread with Richard Labs (who designed ATDL, I believe), support for repeating group in the multileg context seems to be quite sparse.  Thank you for the info!

**Comment by neerajdubey** [comment]
By when we can expect to support repeating group implementation?

**Comment by atdl4net** [comment]
I am sorry, but this software is no longer being actively maintained.  So unless you plan to do it yourself, at no time can you expect repeating group implementation; please see above related comment from @ghost.  Note that the software is now published under the MIT License, so it's perhaps more straightforward if someone wants to fork and do their own thing.
