### ISSUE TITLE
Do we have any sample C# project to support v1.2 atdl

### ISSUE THREAD

**Issue by neerajdubey** [atdl4net/atdl4net#5]
I am using v1.1 fixatdl with the C# project provided by the community, but now I want to support pair, leg trading support to my application, which is possible by v1.2, but the c# application needs to update in v1.2 to support new tags of v1.2 fixatdl.

Also posted the another fix community https://github.com/FIXTradingCommunity/fixatdl-specification/issues/31

Any help would be highly appreciated.

**Comment by atdl4net** [comment]
The README at the root of the project has been updated to clarify the status of this project.  There are no plans to support v1.2 of FIXatdl, sorry.
