### ISSUE TITLE
MIT licensing

### ISSUE THREAD

**Issue by florian-gandon** [atdl4net/atdl4net#6]
Hello !

I see in the README file that MIT licensing is on its way.
The license still mention LGPL and commercial. I guess the commercial one is outdated as there is no more commercial.txt file.

Is there a pull-request ? Or can I, for instance, propose one to use MIT license ?

Regards,
Florian

**Comment by atdl4net** [comment]
Hi.  I have updated the licensing information at the project root to show it is now licensed under the MIT License.

Enjoy.

**Comment by atdl4net** [comment]
Completed

**Comment by florian-gandon** [comment]
Thank you !
